### ISSUE TITLE
Facing NoClassDefFoundError

### ISSUE THREAD

**Issue by zeero0** [saltedge/saltedge-android#32]
Demo app crashes continuously due to NoClassDefFoundError. 

Here is the log:

2018-11-08 14:58:15.565 4100-4100/sdk.saltedge.com.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sdk.saltedge.com.sample, PID: 4100
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/saltedge/sdk/connector/CustomerConnector;
        at com.saltedge.sdk.network.SERequestManager.createCustomer(SERequestManager.java:75)
        at com.saltedge.sdk.sample.features.StartActivity.createCustomer(StartActivity.java:71)
        at com.saltedge.sdk.sample.features.StartActivity.onCreate(StartActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ConstantinKV** [comment]
Saltedge SDK library require extra dependencies:
``` groovy
implementation 'com.squareup.retrofit2:retrofit:2.4.0'//Network communication
implementation 'com.squareup.retrofit2:converter-gson:2.4.0'//model serializer/deserializer
implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'//Network communication logging
```

**Comment by ConstantinKV** [comment]
@zeero0 please check last version and close issue if you are satisfied

**Comment by ConstantinKV** [comment]
@zeero0 I updated sample app, please check again.

**Comment by zeero0** [comment]
Thanks man its working now but I am getting **Invalid HPKP data** warning.

**Comment by ConstantinKV** [comment]
Clear app preferences from system settings or remove/install app.

**Comment by ConstantinKV** [comment]
if you still face the error then please connect last library version (com.saltedge.sdk:saltedge-library:1.3.4@aar). In the the new version updated error handling, so we can detect error more precisely.

**Comment by ConstantinKV** [comment]
@zeero0 please check your your api key and secret and notify us if you still face the error. If not, close the issue.

**Comment by ConstantinKV** [comment]
Already fixed. If you have some extra questions, feel free to ask us.
